# This workflow will build, test and a MuleSoft project and deploy it to the CloudHub

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build, Test, Deploy to CloudHub
      run: mvn clean deploy -DmuleDeploy -Dusername=${{secrets.USERNAME}} -Dpassword=${{secrets.PASSWORD}}
